services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\RSSFeedCollectBundle\Repository\:
    resource: '../../Repository/'
  Tourze\RSSFeedCollectBundle\Service\:
    resource: '../../Service/'
  Tourze\RSSFeedCollectBundle\Command\:
    resource: '../../Command/'
  Tourze\RSSFeedCollectBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  Tourze\RSSFeedCollectBundle\Controller\:
    resource: '../../Controller/'
